print failure message if preview not deployed

diff --git a/.github/workflows/deploy-preview.yaml b/.github/workflows/deploy-preview.yaml
--- a/.github/workflows/deploy-preview.yaml
+++ b/.github/workflows/deploy-preview.yaml
@@ -27,7 +27,7 @@ jobs:
             cp .github/scripts/deploy-preview.sh .
             echo "Running deploy-preview.sh"
             chmod +x deploy-preview.sh
-            ./deploy-preview.sh
+            ./deploy-preview.sh || echo "Failed to deploy preview"
             echo "Performing cleanup..."
             cd ~
             echo "Remove repository"
